/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as appRouteRouteImport } from './../routes/(app)/route'
import { Route as appIndexRouteImport } from './../routes/(app)/index'
import { Route as authSignupRouteImport } from './../routes/(auth)/signup'
import { Route as authLoginRouteImport } from './../routes/(auth)/login'
import { Route as appTeamsRouteImport } from './../routes/(app)/teams'
import { Route as appStaffRouteImport } from './../routes/(app)/staff'
import { Route as appSettingsRouteImport } from './../routes/(app)/settings'
import { Route as appReportsRouteImport } from './../routes/(app)/reports'
import { Route as appPlayersRouteImport } from './../routes/(app)/players'
import { Route as appLeaguesRouteImport } from './../routes/(app)/leagues'
import { Route as appFacilitiesRouteImport } from './../routes/(app)/facilities'
import { Route as appDashboardRouteImport } from './../routes/(app)/dashboard'
import { Route as appAnalyticsRouteImport } from './../routes/(app)/analytics'
import { Route as appAcceptInvitationRouteImport } from './../routes/(app)/accept-invitation'
import { Route as appAboutRouteImport } from './../routes/(app)/about'
import { Route as appTeamsIndexRouteImport } from './../routes/(app)/teams.index'
import { Route as appStaffIndexRouteImport } from './../routes/(app)/staff.index'
import { Route as appLeaguesIndexRouteImport } from './../routes/(app)/leagues.index'
import { Route as appFacilitiesIndexRouteImport } from './../routes/(app)/facilities.index'
import { Route as appTeamsCreateRouteImport } from './../routes/(app)/teams.create'
import { Route as appTeamsTeamSlugRouteImport } from './../routes/(app)/teams.$teamSlug'
import { Route as appStaffCreateRouteImport } from './../routes/(app)/staff.create'
import { Route as appLeaguesCreateRouteImport } from './../routes/(app)/leagues.create'
import { Route as appLeaguesLeagueIdRouteImport } from './../routes/(app)/leagues.$leagueId'
import { Route as appFacilitiesCreateRouteImport } from './../routes/(app)/facilities.create'
import { Route as appFacilitiesFacilityIdRouteImport } from './../routes/(app)/facilities.$facilityId'
import { Route as appTeamsTeamSlugIndexRouteImport } from './../routes/(app)/teams.$teamSlug.index'
import { Route as appLeaguesLeagueIdIndexRouteImport } from './../routes/(app)/leagues.$leagueId.index'
import { Route as appFacilitiesFacilityIdIndexRouteImport } from './../routes/(app)/facilities.$facilityId.index'
import { Route as appTeamsTeamSlugPlayersRouteImport } from './../routes/(app)/teams.$teamSlug.players'
import { Route as appLeaguesLeagueIdTeamsRouteImport } from './../routes/(app)/leagues.$leagueId.teams'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appTeamsRoute = appTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => appRouteRoute,
} as any)
const appStaffRoute = appStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportsRoute = appReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => appRouteRoute,
} as any)
const appPlayersRoute = appPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => appRouteRoute,
} as any)
const appLeaguesRoute = appLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => appRouteRoute,
} as any)
const appFacilitiesRoute = appFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appAnalyticsRoute = appAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => appRouteRoute,
} as any)
const appAcceptInvitationRoute = appAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => appRouteRoute,
} as any)
const appAboutRoute = appAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appRouteRoute,
} as any)
const appTeamsIndexRoute = appTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appTeamsRoute,
} as any)
const appStaffIndexRoute = appStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appStaffRoute,
} as any)
const appLeaguesIndexRoute = appLeaguesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLeaguesRoute,
} as any)
const appFacilitiesIndexRoute = appFacilitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appFacilitiesRoute,
} as any)
const appTeamsCreateRoute = appTeamsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appTeamsRoute,
} as any)
const appTeamsTeamSlugRoute = appTeamsTeamSlugRouteImport.update({
  id: '/$teamSlug',
  path: '/$teamSlug',
  getParentRoute: () => appTeamsRoute,
} as any)
const appStaffCreateRoute = appStaffCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appStaffRoute,
} as any)
const appLeaguesCreateRoute = appLeaguesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appLeaguesRoute,
} as any)
const appLeaguesLeagueIdRoute = appLeaguesLeagueIdRouteImport.update({
  id: '/$leagueId',
  path: '/$leagueId',
  getParentRoute: () => appLeaguesRoute,
} as any)
const appFacilitiesCreateRoute = appFacilitiesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appFacilitiesRoute,
} as any)
const appFacilitiesFacilityIdRoute = appFacilitiesFacilityIdRouteImport.update({
  id: '/$facilityId',
  path: '/$facilityId',
  getParentRoute: () => appFacilitiesRoute,
} as any)
const appTeamsTeamSlugIndexRoute = appTeamsTeamSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appTeamsTeamSlugRoute,
} as any)
const appLeaguesLeagueIdIndexRoute = appLeaguesLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLeaguesLeagueIdRoute,
} as any)
const appFacilitiesFacilityIdIndexRoute =
  appFacilitiesFacilityIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appFacilitiesFacilityIdRoute,
  } as any)
const appTeamsTeamSlugPlayersRoute = appTeamsTeamSlugPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => appTeamsTeamSlugRoute,
} as any)
const appLeaguesLeagueIdTeamsRoute = appLeaguesLeagueIdTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => appLeaguesLeagueIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof appAboutRoute
  '/accept-invitation': typeof appAcceptInvitationRoute
  '/analytics': typeof appAnalyticsRoute
  '/dashboard': typeof appDashboardRoute
  '/facilities': typeof appFacilitiesRouteWithChildren
  '/leagues': typeof appLeaguesRouteWithChildren
  '/players': typeof appPlayersRoute
  '/reports': typeof appReportsRoute
  '/settings': typeof appSettingsRoute
  '/staff': typeof appStaffRouteWithChildren
  '/teams': typeof appTeamsRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/facilities/$facilityId': typeof appFacilitiesFacilityIdRouteWithChildren
  '/facilities/create': typeof appFacilitiesCreateRoute
  '/leagues/$leagueId': typeof appLeaguesLeagueIdRouteWithChildren
  '/leagues/create': typeof appLeaguesCreateRoute
  '/staff/create': typeof appStaffCreateRoute
  '/teams/$teamSlug': typeof appTeamsTeamSlugRouteWithChildren
  '/teams/create': typeof appTeamsCreateRoute
  '/facilities/': typeof appFacilitiesIndexRoute
  '/leagues/': typeof appLeaguesIndexRoute
  '/staff/': typeof appStaffIndexRoute
  '/teams/': typeof appTeamsIndexRoute
  '/leagues/$leagueId/teams': typeof appLeaguesLeagueIdTeamsRoute
  '/teams/$teamSlug/players': typeof appTeamsTeamSlugPlayersRoute
  '/facilities/$facilityId/': typeof appFacilitiesFacilityIdIndexRoute
  '/leagues/$leagueId/': typeof appLeaguesLeagueIdIndexRoute
  '/teams/$teamSlug/': typeof appTeamsTeamSlugIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof appAboutRoute
  '/accept-invitation': typeof appAcceptInvitationRoute
  '/analytics': typeof appAnalyticsRoute
  '/dashboard': typeof appDashboardRoute
  '/players': typeof appPlayersRoute
  '/reports': typeof appReportsRoute
  '/settings': typeof appSettingsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/facilities/create': typeof appFacilitiesCreateRoute
  '/leagues/create': typeof appLeaguesCreateRoute
  '/staff/create': typeof appStaffCreateRoute
  '/teams/create': typeof appTeamsCreateRoute
  '/facilities': typeof appFacilitiesIndexRoute
  '/leagues': typeof appLeaguesIndexRoute
  '/staff': typeof appStaffIndexRoute
  '/teams': typeof appTeamsIndexRoute
  '/leagues/$leagueId/teams': typeof appLeaguesLeagueIdTeamsRoute
  '/teams/$teamSlug/players': typeof appTeamsTeamSlugPlayersRoute
  '/facilities/$facilityId': typeof appFacilitiesFacilityIdIndexRoute
  '/leagues/$leagueId': typeof appLeaguesLeagueIdIndexRoute
  '/teams/$teamSlug': typeof appTeamsTeamSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/about': typeof appAboutRoute
  '/(app)/accept-invitation': typeof appAcceptInvitationRoute
  '/(app)/analytics': typeof appAnalyticsRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/facilities': typeof appFacilitiesRouteWithChildren
  '/(app)/leagues': typeof appLeaguesRouteWithChildren
  '/(app)/players': typeof appPlayersRoute
  '/(app)/reports': typeof appReportsRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(app)/staff': typeof appStaffRouteWithChildren
  '/(app)/teams': typeof appTeamsRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/facilities/$facilityId': typeof appFacilitiesFacilityIdRouteWithChildren
  '/(app)/facilities/create': typeof appFacilitiesCreateRoute
  '/(app)/leagues/$leagueId': typeof appLeaguesLeagueIdRouteWithChildren
  '/(app)/leagues/create': typeof appLeaguesCreateRoute
  '/(app)/staff/create': typeof appStaffCreateRoute
  '/(app)/teams/$teamSlug': typeof appTeamsTeamSlugRouteWithChildren
  '/(app)/teams/create': typeof appTeamsCreateRoute
  '/(app)/facilities/': typeof appFacilitiesIndexRoute
  '/(app)/leagues/': typeof appLeaguesIndexRoute
  '/(app)/staff/': typeof appStaffIndexRoute
  '/(app)/teams/': typeof appTeamsIndexRoute
  '/(app)/leagues/$leagueId/teams': typeof appLeaguesLeagueIdTeamsRoute
  '/(app)/teams/$teamSlug/players': typeof appTeamsTeamSlugPlayersRoute
  '/(app)/facilities/$facilityId/': typeof appFacilitiesFacilityIdIndexRoute
  '/(app)/leagues/$leagueId/': typeof appLeaguesLeagueIdIndexRoute
  '/(app)/teams/$teamSlug/': typeof appTeamsTeamSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/accept-invitation'
    | '/analytics'
    | '/dashboard'
    | '/facilities'
    | '/leagues'
    | '/players'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/teams'
    | '/login'
    | '/signup'
    | '/'
    | '/facilities/$facilityId'
    | '/facilities/create'
    | '/leagues/$leagueId'
    | '/leagues/create'
    | '/staff/create'
    | '/teams/$teamSlug'
    | '/teams/create'
    | '/facilities/'
    | '/leagues/'
    | '/staff/'
    | '/teams/'
    | '/leagues/$leagueId/teams'
    | '/teams/$teamSlug/players'
    | '/facilities/$facilityId/'
    | '/leagues/$leagueId/'
    | '/teams/$teamSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/accept-invitation'
    | '/analytics'
    | '/dashboard'
    | '/players'
    | '/reports'
    | '/settings'
    | '/login'
    | '/signup'
    | '/'
    | '/facilities/create'
    | '/leagues/create'
    | '/staff/create'
    | '/teams/create'
    | '/facilities'
    | '/leagues'
    | '/staff'
    | '/teams'
    | '/leagues/$leagueId/teams'
    | '/teams/$teamSlug/players'
    | '/facilities/$facilityId'
    | '/leagues/$leagueId'
    | '/teams/$teamSlug'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/about'
    | '/(app)/accept-invitation'
    | '/(app)/analytics'
    | '/(app)/dashboard'
    | '/(app)/facilities'
    | '/(app)/leagues'
    | '/(app)/players'
    | '/(app)/reports'
    | '/(app)/settings'
    | '/(app)/staff'
    | '/(app)/teams'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(app)/'
    | '/(app)/facilities/$facilityId'
    | '/(app)/facilities/create'
    | '/(app)/leagues/$leagueId'
    | '/(app)/leagues/create'
    | '/(app)/staff/create'
    | '/(app)/teams/$teamSlug'
    | '/(app)/teams/create'
    | '/(app)/facilities/'
    | '/(app)/leagues/'
    | '/(app)/staff/'
    | '/(app)/teams/'
    | '/(app)/leagues/$leagueId/teams'
    | '/(app)/teams/$teamSlug/players'
    | '/(app)/facilities/$facilityId/'
    | '/(app)/leagues/$leagueId/'
    | '/(app)/teams/$teamSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/teams': {
      id: '/(app)/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof appTeamsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/staff': {
      id: '/(app)/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof appStaffRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/reports': {
      id: '/(app)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof appReportsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/players': {
      id: '/(app)/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof appPlayersRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/leagues': {
      id: '/(app)/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof appLeaguesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/facilities': {
      id: '/(app)/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof appFacilitiesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/analytics': {
      id: '/(app)/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof appAnalyticsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/accept-invitation': {
      id: '/(app)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof appAcceptInvitationRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/about': {
      id: '/(app)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appAboutRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/teams/': {
      id: '/(app)/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof appTeamsIndexRouteImport
      parentRoute: typeof appTeamsRoute
    }
    '/(app)/staff/': {
      id: '/(app)/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof appStaffIndexRouteImport
      parentRoute: typeof appStaffRoute
    }
    '/(app)/leagues/': {
      id: '/(app)/leagues/'
      path: '/'
      fullPath: '/leagues/'
      preLoaderRoute: typeof appLeaguesIndexRouteImport
      parentRoute: typeof appLeaguesRoute
    }
    '/(app)/facilities/': {
      id: '/(app)/facilities/'
      path: '/'
      fullPath: '/facilities/'
      preLoaderRoute: typeof appFacilitiesIndexRouteImport
      parentRoute: typeof appFacilitiesRoute
    }
    '/(app)/teams/create': {
      id: '/(app)/teams/create'
      path: '/create'
      fullPath: '/teams/create'
      preLoaderRoute: typeof appTeamsCreateRouteImport
      parentRoute: typeof appTeamsRoute
    }
    '/(app)/teams/$teamSlug': {
      id: '/(app)/teams/$teamSlug'
      path: '/$teamSlug'
      fullPath: '/teams/$teamSlug'
      preLoaderRoute: typeof appTeamsTeamSlugRouteImport
      parentRoute: typeof appTeamsRoute
    }
    '/(app)/staff/create': {
      id: '/(app)/staff/create'
      path: '/create'
      fullPath: '/staff/create'
      preLoaderRoute: typeof appStaffCreateRouteImport
      parentRoute: typeof appStaffRoute
    }
    '/(app)/leagues/create': {
      id: '/(app)/leagues/create'
      path: '/create'
      fullPath: '/leagues/create'
      preLoaderRoute: typeof appLeaguesCreateRouteImport
      parentRoute: typeof appLeaguesRoute
    }
    '/(app)/leagues/$leagueId': {
      id: '/(app)/leagues/$leagueId'
      path: '/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof appLeaguesLeagueIdRouteImport
      parentRoute: typeof appLeaguesRoute
    }
    '/(app)/facilities/create': {
      id: '/(app)/facilities/create'
      path: '/create'
      fullPath: '/facilities/create'
      preLoaderRoute: typeof appFacilitiesCreateRouteImport
      parentRoute: typeof appFacilitiesRoute
    }
    '/(app)/facilities/$facilityId': {
      id: '/(app)/facilities/$facilityId'
      path: '/$facilityId'
      fullPath: '/facilities/$facilityId'
      preLoaderRoute: typeof appFacilitiesFacilityIdRouteImport
      parentRoute: typeof appFacilitiesRoute
    }
    '/(app)/teams/$teamSlug/': {
      id: '/(app)/teams/$teamSlug/'
      path: '/'
      fullPath: '/teams/$teamSlug/'
      preLoaderRoute: typeof appTeamsTeamSlugIndexRouteImport
      parentRoute: typeof appTeamsTeamSlugRoute
    }
    '/(app)/leagues/$leagueId/': {
      id: '/(app)/leagues/$leagueId/'
      path: '/'
      fullPath: '/leagues/$leagueId/'
      preLoaderRoute: typeof appLeaguesLeagueIdIndexRouteImport
      parentRoute: typeof appLeaguesLeagueIdRoute
    }
    '/(app)/facilities/$facilityId/': {
      id: '/(app)/facilities/$facilityId/'
      path: '/'
      fullPath: '/facilities/$facilityId/'
      preLoaderRoute: typeof appFacilitiesFacilityIdIndexRouteImport
      parentRoute: typeof appFacilitiesFacilityIdRoute
    }
    '/(app)/teams/$teamSlug/players': {
      id: '/(app)/teams/$teamSlug/players'
      path: '/players'
      fullPath: '/teams/$teamSlug/players'
      preLoaderRoute: typeof appTeamsTeamSlugPlayersRouteImport
      parentRoute: typeof appTeamsTeamSlugRoute
    }
    '/(app)/leagues/$leagueId/teams': {
      id: '/(app)/leagues/$leagueId/teams'
      path: '/teams'
      fullPath: '/leagues/$leagueId/teams'
      preLoaderRoute: typeof appLeaguesLeagueIdTeamsRouteImport
      parentRoute: typeof appLeaguesLeagueIdRoute
    }
  }
}

interface appFacilitiesFacilityIdRouteChildren {
  appFacilitiesFacilityIdIndexRoute: typeof appFacilitiesFacilityIdIndexRoute
}

const appFacilitiesFacilityIdRouteChildren: appFacilitiesFacilityIdRouteChildren =
  {
    appFacilitiesFacilityIdIndexRoute: appFacilitiesFacilityIdIndexRoute,
  }

const appFacilitiesFacilityIdRouteWithChildren =
  appFacilitiesFacilityIdRoute._addFileChildren(
    appFacilitiesFacilityIdRouteChildren,
  )

interface appFacilitiesRouteChildren {
  appFacilitiesFacilityIdRoute: typeof appFacilitiesFacilityIdRouteWithChildren
  appFacilitiesCreateRoute: typeof appFacilitiesCreateRoute
  appFacilitiesIndexRoute: typeof appFacilitiesIndexRoute
}

const appFacilitiesRouteChildren: appFacilitiesRouteChildren = {
  appFacilitiesFacilityIdRoute: appFacilitiesFacilityIdRouteWithChildren,
  appFacilitiesCreateRoute: appFacilitiesCreateRoute,
  appFacilitiesIndexRoute: appFacilitiesIndexRoute,
}

const appFacilitiesRouteWithChildren = appFacilitiesRoute._addFileChildren(
  appFacilitiesRouteChildren,
)

interface appLeaguesLeagueIdRouteChildren {
  appLeaguesLeagueIdTeamsRoute: typeof appLeaguesLeagueIdTeamsRoute
  appLeaguesLeagueIdIndexRoute: typeof appLeaguesLeagueIdIndexRoute
}

const appLeaguesLeagueIdRouteChildren: appLeaguesLeagueIdRouteChildren = {
  appLeaguesLeagueIdTeamsRoute: appLeaguesLeagueIdTeamsRoute,
  appLeaguesLeagueIdIndexRoute: appLeaguesLeagueIdIndexRoute,
}

const appLeaguesLeagueIdRouteWithChildren =
  appLeaguesLeagueIdRoute._addFileChildren(appLeaguesLeagueIdRouteChildren)

interface appLeaguesRouteChildren {
  appLeaguesLeagueIdRoute: typeof appLeaguesLeagueIdRouteWithChildren
  appLeaguesCreateRoute: typeof appLeaguesCreateRoute
  appLeaguesIndexRoute: typeof appLeaguesIndexRoute
}

const appLeaguesRouteChildren: appLeaguesRouteChildren = {
  appLeaguesLeagueIdRoute: appLeaguesLeagueIdRouteWithChildren,
  appLeaguesCreateRoute: appLeaguesCreateRoute,
  appLeaguesIndexRoute: appLeaguesIndexRoute,
}

const appLeaguesRouteWithChildren = appLeaguesRoute._addFileChildren(
  appLeaguesRouteChildren,
)

interface appStaffRouteChildren {
  appStaffCreateRoute: typeof appStaffCreateRoute
  appStaffIndexRoute: typeof appStaffIndexRoute
}

const appStaffRouteChildren: appStaffRouteChildren = {
  appStaffCreateRoute: appStaffCreateRoute,
  appStaffIndexRoute: appStaffIndexRoute,
}

const appStaffRouteWithChildren = appStaffRoute._addFileChildren(
  appStaffRouteChildren,
)

interface appTeamsTeamSlugRouteChildren {
  appTeamsTeamSlugPlayersRoute: typeof appTeamsTeamSlugPlayersRoute
  appTeamsTeamSlugIndexRoute: typeof appTeamsTeamSlugIndexRoute
}

const appTeamsTeamSlugRouteChildren: appTeamsTeamSlugRouteChildren = {
  appTeamsTeamSlugPlayersRoute: appTeamsTeamSlugPlayersRoute,
  appTeamsTeamSlugIndexRoute: appTeamsTeamSlugIndexRoute,
}

const appTeamsTeamSlugRouteWithChildren =
  appTeamsTeamSlugRoute._addFileChildren(appTeamsTeamSlugRouteChildren)

interface appTeamsRouteChildren {
  appTeamsTeamSlugRoute: typeof appTeamsTeamSlugRouteWithChildren
  appTeamsCreateRoute: typeof appTeamsCreateRoute
  appTeamsIndexRoute: typeof appTeamsIndexRoute
}

const appTeamsRouteChildren: appTeamsRouteChildren = {
  appTeamsTeamSlugRoute: appTeamsTeamSlugRouteWithChildren,
  appTeamsCreateRoute: appTeamsCreateRoute,
  appTeamsIndexRoute: appTeamsIndexRoute,
}

const appTeamsRouteWithChildren = appTeamsRoute._addFileChildren(
  appTeamsRouteChildren,
)

interface appRouteRouteChildren {
  appAboutRoute: typeof appAboutRoute
  appAcceptInvitationRoute: typeof appAcceptInvitationRoute
  appAnalyticsRoute: typeof appAnalyticsRoute
  appDashboardRoute: typeof appDashboardRoute
  appFacilitiesRoute: typeof appFacilitiesRouteWithChildren
  appLeaguesRoute: typeof appLeaguesRouteWithChildren
  appPlayersRoute: typeof appPlayersRoute
  appReportsRoute: typeof appReportsRoute
  appSettingsRoute: typeof appSettingsRoute
  appStaffRoute: typeof appStaffRouteWithChildren
  appTeamsRoute: typeof appTeamsRouteWithChildren
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAboutRoute: appAboutRoute,
  appAcceptInvitationRoute: appAcceptInvitationRoute,
  appAnalyticsRoute: appAnalyticsRoute,
  appDashboardRoute: appDashboardRoute,
  appFacilitiesRoute: appFacilitiesRouteWithChildren,
  appLeaguesRoute: appLeaguesRouteWithChildren,
  appPlayersRoute: appPlayersRoute,
  appReportsRoute: appReportsRoute,
  appSettingsRoute: appSettingsRoute,
  appStaffRoute: appStaffRouteWithChildren,
  appTeamsRoute: appTeamsRouteWithChildren,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
