/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as appRouteRouteImport } from './../routes/(app)/route'
import { Route as appIndexRouteImport } from './../routes/(app)/index'
import { Route as authSignupRouteImport } from './../routes/(auth)/signup'
import { Route as authLoginRouteImport } from './../routes/(auth)/login'
import { Route as appTeamsRouteImport } from './../routes/(app)/teams'
import { Route as appStaffRouteImport } from './../routes/(app)/staff'
import { Route as appSettingsRouteImport } from './../routes/(app)/settings'
import { Route as appReportsRouteImport } from './../routes/(app)/reports'
import { Route as appPlayersRouteImport } from './../routes/(app)/players'
import { Route as appDashboardRouteImport } from './../routes/(app)/dashboard'
import { Route as appAnalyticsRouteImport } from './../routes/(app)/analytics'
import { Route as appAcceptInvitationRouteImport } from './../routes/(app)/accept-invitation'
import { Route as appAboutRouteImport } from './../routes/(app)/about'
import { Route as appTeamsIndexRouteImport } from './../routes/(app)/teams.index'
import { Route as appStaffIndexRouteImport } from './../routes/(app)/staff.index'
import { Route as appTeamsCreateRouteImport } from './../routes/(app)/teams.create'
import { Route as appStaffCreateRouteImport } from './../routes/(app)/staff.create'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appTeamsRoute = appTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => appRouteRoute,
} as any)
const appStaffRoute = appStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportsRoute = appReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => appRouteRoute,
} as any)
const appPlayersRoute = appPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appAnalyticsRoute = appAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => appRouteRoute,
} as any)
const appAcceptInvitationRoute = appAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => appRouteRoute,
} as any)
const appAboutRoute = appAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appRouteRoute,
} as any)
const appTeamsIndexRoute = appTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appTeamsRoute,
} as any)
const appStaffIndexRoute = appStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appStaffRoute,
} as any)
const appTeamsCreateRoute = appTeamsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appTeamsRoute,
} as any)
const appStaffCreateRoute = appStaffCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appStaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof appAboutRoute
  '/accept-invitation': typeof appAcceptInvitationRoute
  '/analytics': typeof appAnalyticsRoute
  '/dashboard': typeof appDashboardRoute
  '/players': typeof appPlayersRoute
  '/reports': typeof appReportsRoute
  '/settings': typeof appSettingsRoute
  '/staff': typeof appStaffRouteWithChildren
  '/teams': typeof appTeamsRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/staff/create': typeof appStaffCreateRoute
  '/teams/create': typeof appTeamsCreateRoute
  '/staff/': typeof appStaffIndexRoute
  '/teams/': typeof appTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof appAboutRoute
  '/accept-invitation': typeof appAcceptInvitationRoute
  '/analytics': typeof appAnalyticsRoute
  '/dashboard': typeof appDashboardRoute
  '/players': typeof appPlayersRoute
  '/reports': typeof appReportsRoute
  '/settings': typeof appSettingsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/staff/create': typeof appStaffCreateRoute
  '/teams/create': typeof appTeamsCreateRoute
  '/staff': typeof appStaffIndexRoute
  '/teams': typeof appTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/about': typeof appAboutRoute
  '/(app)/accept-invitation': typeof appAcceptInvitationRoute
  '/(app)/analytics': typeof appAnalyticsRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/players': typeof appPlayersRoute
  '/(app)/reports': typeof appReportsRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(app)/staff': typeof appStaffRouteWithChildren
  '/(app)/teams': typeof appTeamsRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/staff/create': typeof appStaffCreateRoute
  '/(app)/teams/create': typeof appTeamsCreateRoute
  '/(app)/staff/': typeof appStaffIndexRoute
  '/(app)/teams/': typeof appTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/accept-invitation'
    | '/analytics'
    | '/dashboard'
    | '/players'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/teams'
    | '/login'
    | '/signup'
    | '/'
    | '/staff/create'
    | '/teams/create'
    | '/staff/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/accept-invitation'
    | '/analytics'
    | '/dashboard'
    | '/players'
    | '/reports'
    | '/settings'
    | '/login'
    | '/signup'
    | '/'
    | '/staff/create'
    | '/teams/create'
    | '/staff'
    | '/teams'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/about'
    | '/(app)/accept-invitation'
    | '/(app)/analytics'
    | '/(app)/dashboard'
    | '/(app)/players'
    | '/(app)/reports'
    | '/(app)/settings'
    | '/(app)/staff'
    | '/(app)/teams'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(app)/'
    | '/(app)/staff/create'
    | '/(app)/teams/create'
    | '/(app)/staff/'
    | '/(app)/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/teams': {
      id: '/(app)/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof appTeamsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/staff': {
      id: '/(app)/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof appStaffRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/reports': {
      id: '/(app)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof appReportsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/players': {
      id: '/(app)/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof appPlayersRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/analytics': {
      id: '/(app)/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof appAnalyticsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/accept-invitation': {
      id: '/(app)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof appAcceptInvitationRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/about': {
      id: '/(app)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appAboutRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/teams/': {
      id: '/(app)/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof appTeamsIndexRouteImport
      parentRoute: typeof appTeamsRoute
    }
    '/(app)/staff/': {
      id: '/(app)/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof appStaffIndexRouteImport
      parentRoute: typeof appStaffRoute
    }
    '/(app)/teams/create': {
      id: '/(app)/teams/create'
      path: '/create'
      fullPath: '/teams/create'
      preLoaderRoute: typeof appTeamsCreateRouteImport
      parentRoute: typeof appTeamsRoute
    }
    '/(app)/staff/create': {
      id: '/(app)/staff/create'
      path: '/create'
      fullPath: '/staff/create'
      preLoaderRoute: typeof appStaffCreateRouteImport
      parentRoute: typeof appStaffRoute
    }
  }
}

interface appStaffRouteChildren {
  appStaffCreateRoute: typeof appStaffCreateRoute
  appStaffIndexRoute: typeof appStaffIndexRoute
}

const appStaffRouteChildren: appStaffRouteChildren = {
  appStaffCreateRoute: appStaffCreateRoute,
  appStaffIndexRoute: appStaffIndexRoute,
}

const appStaffRouteWithChildren = appStaffRoute._addFileChildren(
  appStaffRouteChildren,
)

interface appTeamsRouteChildren {
  appTeamsCreateRoute: typeof appTeamsCreateRoute
  appTeamsIndexRoute: typeof appTeamsIndexRoute
}

const appTeamsRouteChildren: appTeamsRouteChildren = {
  appTeamsCreateRoute: appTeamsCreateRoute,
  appTeamsIndexRoute: appTeamsIndexRoute,
}

const appTeamsRouteWithChildren = appTeamsRoute._addFileChildren(
  appTeamsRouteChildren,
)

interface appRouteRouteChildren {
  appAboutRoute: typeof appAboutRoute
  appAcceptInvitationRoute: typeof appAcceptInvitationRoute
  appAnalyticsRoute: typeof appAnalyticsRoute
  appDashboardRoute: typeof appDashboardRoute
  appPlayersRoute: typeof appPlayersRoute
  appReportsRoute: typeof appReportsRoute
  appSettingsRoute: typeof appSettingsRoute
  appStaffRoute: typeof appStaffRouteWithChildren
  appTeamsRoute: typeof appTeamsRouteWithChildren
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAboutRoute: appAboutRoute,
  appAcceptInvitationRoute: appAcceptInvitationRoute,
  appAnalyticsRoute: appAnalyticsRoute,
  appDashboardRoute: appDashboardRoute,
  appPlayersRoute: appPlayersRoute,
  appReportsRoute: appReportsRoute,
  appSettingsRoute: appSettingsRoute,
  appStaffRoute: appStaffRouteWithChildren,
  appTeamsRoute: appTeamsRouteWithChildren,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
